# Generated by Django 3.2.5 on 2021-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'girl'), (1, 'boy')])),
                ('age', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
            ],
        ),
    ]
