# Generated by Django 3.2.5 on 2021-09-11 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='weight',
            field=models.FloatField(max_length=3),
        ),
    ]
