# Generated by Django 3.2.5 on 2021-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_auto_20210911_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='height',
            field=models.FloatField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
